FROM node:18-alpine

WORKDIR /usr/src/app

COPY package*.json ./

# Install only production dependencies
RUN npm install --production

COPY . .

# Set environment to production
ENV NODE_ENV=production

EXPOSE 3000

CMD ["npm", "start"]
