version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: travel_diaries_backend_prod
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: always

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    container_name: travel_diaries_frontend_prod
    ports:
      - '80:80'
    restart: always
    depends_on:
      - backend
